name: 'Snowflake Query Runner Action'
author: 'anecdotes.ai / Kirksten3'
description: 'This action lets you run a list of SQL queries against Snowflake. Forked from anecdotes.ai to continue support.'

branding:
  icon: 'database'
  color: 'blue'

inputs:
  snowflake_username:
    description: 'Username for Snowflake'
    required: true
  snowflake_password:
    description: 'Password for Snowflake'
    required: true
  snowflake_account:
    description: 'Account name for Snowflake. Your account name is the full/entire string to the left of snowflakecomputing.com.'
    required: true
  snowflake_warehouse:
    description: 'Warehouse as context'
    required: true
  snowflake_role:
    description: 'Set user role'
    required: false
  queries:
    description: 'List of SQL queries, seperated by ;'
    required: true
  sync:
    description: 'Whether to run the queries sync (default is async)'
    required: false

outputs:
  queries_results:
    description: 'Json encoded as base64, containing all queries results'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
